"""Added missing column 'description' to game

Revision ID: 50bb26d08e71
Revises: 16024ea933fc
Create Date: 2024-07-03 11:25:44.236369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50bb26d08e71'
down_revision: Union[str, None] = '16024ea933fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'description')
    # ### end Alembic commands ###
